version: '3.8'

services:
  app:
    container_name: iov_security
    build: .
    shm_size: '1gb'
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    command: python src/generate_images.py
    # command: python src/main.py